/** Curated emoji set for the chat composer (no external package). */

export type EmojiCategoryId =
  | "recent"
  | "smileys"
  | "gestures"
  | "people"
  | "animals"
  | "food"
  | "travel"
  | "activities"
  | "objects"
  | "symbols"
  | "flags";

export type EmojiItem = {
  e: string;
  n: string; // search name
  k?: string; // extra keywords
};

export type EmojiCategory = {
  id: EmojiCategoryId;
  label: string;
  icon: string;
  items: EmojiItem[];
};

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "😀",
    items: [
      { e: "😀", n: "grinning" },
      { e: "😃", n: "smiley" },
      { e: "😄", n: "smile" },
      { e: "😁", n: "grin" },
      { e: "😆", n: "laughing" },
      { e: "😅", n: "sweat smile" },
      { e: "🤣", n: "rofl" },
      { e: "😂", n: "joy tears" },
      { e: "🙂", n: "slight smile" },
      { e: "🙃", n: "upside down" },
      { e: "😉", n: "wink" },
      { e: "😊", n: "blush" },
      { e: "😇", n: "innocent" },
      { e: "🥰", n: "smiling hearts" },
      { e: "😍", n: "heart eyes" },
      { e: "🤩", n: "star struck" },
      { e: "😘", n: "kiss" },
      { e: "😗", n: "kissing" },
      { e: "😚", n: "kissing closed" },
      { e: "😙", n: "kissing smile" },
      { e: "🥲", n: "tear smile" },
      { e: "😋", n: "yum" },
      { e: "😛", n: "tongue" },
      { e: "😜", n: "wink tongue" },
      { e: "🤪", n: "zany" },
      { e: "😝", n: "squint tongue" },
      { e: "🤑", n: "money mouth" },
      { e: "🤗", n: "hug" },
      { e: "🤭", n: "hand over mouth" },
      { e: "🤫", n: "shush" },
      { e: "🤔", n: "thinking" },
      { e: "🤐", n: "zipper mouth" },
      { e: "🤨", n: "raised eyebrow" },
      { e: "😐", n: "neutral" },
      { e: "😑", n: "expressionless" },
      { e: "😶", n: "no mouth" },
      { e: "😏", n: "smirk" },
      { e: "😒", n: "unamused" },
      { e: "🙄", n: "eye roll" },
      { e: "😬", n: "grimace" },
      { e: "😮‍💨", n: "exhale" },
      { e: "🤥", n: "lying" },
      { e: "😌", n: "relieved" },
      { e: "😔", n: "pensive" },
      { e: "😪", n: "sleepy" },
      { e: "🤤", n: "drooling" },
      { e: "😴", n: "sleeping" },
      { e: "😷", n: "mask" },
      { e: "🤒", n: "thermometer" },
      { e: "🤕", n: "head bandage" },
      { e: "🤢", n: "nauseated" },
      { e: "🤮", n: "vomit" },
      { e: "🤧", n: "sneeze" },
      { e: "🥵", n: "hot" },
      { e: "🥶", n: "cold" },
      { e: "🥴", n: "woozy" },
      { e: "😵", n: "dizzy" },
      { e: "🤯", n: "exploding head" },
      { e: "🤠", n: "cowboy" },
      { e: "🥳", n: "party" },
      { e: "🥸", n: "disguise" },
      { e: "😎", n: "sunglasses cool" },
      { e: "🤓", n: "nerd" },
      { e: "🧐", n: "monocle" },
      { e: "😕", n: "confused" },
      { e: "😟", n: "worried" },
      { e: "🙁", n: "slight frown" },
      { e: "☹️", n: "frown" },
      { e: "😮", n: "open mouth" },
      { e: "😯", n: "hushed" },
      { e: "😲", n: "astonished" },
      { e: "😳", n: "flushed" },
      { e: "🥺", n: "pleading" },
      { e: "😦", n: "frowning open" },
      { e: "😧", n: "anguished" },
      { e: "😨", n: "fearful" },
      { e: "😰", n: "anxious sweat" },
      { e: "😥", n: "sad relieved" },
      { e: "😢", n: "cry" },
      { e: "😭", n: "sob" },
      { e: "😱", n: "scream" },
      { e: "😖", n: "confounded" },
      { e: "😣", n: "persevere" },
      { e: "😞", n: "disappointed" },
      { e: "😓", n: "downcast" },
      { e: "😩", n: "weary" },
      { e: "😫", n: "tired" },
      { e: "🥱", n: "yawn" },
      { e: "😤", n: "triumph" },
      { e: "😡", n: "pout rage" },
      { e: "😠", n: "angry" },
      { e: "🤬", n: "cursing" },
      { e: "😈", n: "smiling devil" },
      { e: "👿", n: "angry devil" },
      { e: "💀", n: "skull" },
      { e: "☠️", n: "skull crossbones" },
      { e: "💩", n: "poop" },
      { e: "🤡", n: "clown" },
      { e: "👹", n: "ogre" },
      { e: "👺", n: "goblin" },
      { e: "👻", n: "ghost" },
      { e: "👽", n: "alien" },
      { e: "👾", n: "space invader" },
      { e: "🤖", n: "robot" },
      { e: "🎃", n: "jack o lantern" },
      { e: "😺", n: "cat grin" },
      { e: "😸", n: "cat smile" },
      { e: "😹", n: "cat joy" },
      { e: "😻", n: "cat heart eyes" },
      { e: "😼", n: "cat smirk" },
      { e: "😽", n: "cat kiss" },
      { e: "🙀", n: "cat scream" },
      { e: "😿", n: "cat cry" },
      { e: "😾", n: "cat pout" },
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    icon: "👍",
    items: [
      { e: "👋", n: "wave" },
      { e: "🤚", n: "raised back hand" },
      { e: "🖐️", n: "hand splayed" },
      { e: "✋", n: "raised hand" },
      { e: "🖖", n: "vulcan" },
      { e: "👌", n: "ok hand" },
      { e: "🤌", n: "pinched fingers" },
      { e: "🤏", n: "pinching hand" },
      { e: "✌️", n: "victory" },
      { e: "🤞", n: "crossed fingers" },
      { e: "🤟", n: "love you" },
      { e: "🤘", n: "rock on" },
      { e: "🤙", n: "call me" },
      { e: "👈", n: "point left" },
      { e: "👉", n: "point right" },
      { e: "👆", n: "point up" },
      { e: "🖕", n: "middle finger" },
      { e: "👇", n: "point down" },
      { e: "☝️", n: "index up" },
      { e: "👍", n: "thumbs up yes" },
      { e: "👎", n: "thumbs down no" },
      { e: "✊", n: "fist" },
      { e: "👊", n: "punch" },
      { e: "🤛", n: "left fist" },
      { e: "🤜", n: "right fist" },
      { e: "👏", n: "clap" },
      { e: "🙌", n: "raised hands" },
      { e: "👐", n: "open hands" },
      { e: "🤲", n: "palms up" },
      { e: "🤝", n: "handshake" },
      { e: "🙏", n: "pray thanks" },
      { e: "✍️", n: "writing" },
      { e: "💅", n: "nail polish" },
      { e: "🤳", n: "selfie" },
      { e: "💪", n: "muscle strong" },
      { e: "🦾", n: "mechanical arm" },
      { e: "🦿", n: "mechanical leg" },
      { e: "🦵", n: "leg" },
      { e: "🦶", n: "foot" },
      { e: "👂", n: "ear" },
      { e: "🦻", n: "hearing aid" },
      { e: "👃", n: "nose" },
      { e: "🧠", n: "brain" },
      { e: "🫀", n: "heart organ" },
      { e: "🫁", n: "lungs" },
      { e: "🦷", n: "tooth" },
      { e: "🦴", n: "bone" },
      { e: "👀", n: "eyes" },
      { e: "👁️", n: "eye" },
      { e: "👅", n: "tongue body" },
      { e: "👄", n: "mouth" },
      { e: "💋", n: "kiss mark" },
      { e: "🩸", n: "blood drop" },
    ],
  },
  {
    id: "people",
    label: "People",
    icon: "🧑",
    items: [
      { e: "👶", n: "baby" },
      { e: "🧒", n: "child" },
      { e: "👦", n: "boy" },
      { e: "👧", n: "girl" },
      { e: "🧑", n: "person" },
      { e: "👱", n: "blond" },
      { e: "👨", n: "man" },
      { e: "🧔", n: "beard" },
      { e: "👩", n: "woman" },
      { e: "🧓", n: "older person" },
      { e: "👴", n: "old man" },
      { e: "👵", n: "old woman" },
      { e: "🙍", n: "frowning person" },
      { e: "🙎", n: "pouting person" },
      { e: "🙅", n: "no gesture" },
      { e: "🙆", n: "ok gesture" },
      { e: "💁", n: "tipping hand" },
      { e: "🙋", n: "raising hand" },
      { e: "🧏", n: "deaf" },
      { e: "🙇", n: "bow" },
      { e: "🤦", n: "facepalm" },
      { e: "🤷", n: "shrug" },
      { e: "🧑‍⚕️", n: "health worker" },
      { e: "🧑‍🎓", n: "student" },
      { e: "🧑‍💻", n: "technologist coder" },
      { e: "🧑‍🔬", n: "scientist" },
      { e: "🧑‍🚀", n: "astronaut" },
      { e: "🧑‍🚒", n: "firefighter" },
      { e: "👮", n: "police" },
      { e: "🕵️", n: "detective" },
      { e: "💂", n: "guard" },
      { e: "🥷", n: "ninja" },
      { e: "👷", n: "construction" },
      { e: "🤴", n: "prince" },
      { e: "👸", n: "princess" },
      { e: "👳", n: "turban" },
      { e: "👲", n: "skullcap" },
      { e: "🧕", n: "headscarf" },
      { e: "🤵", n: "tuxedo" },
      { e: "👰", n: "bride" },
      { e: "🤰", n: "pregnant" },
      { e: "🤱", n: "breast feeding" },
      { e: "👼", n: "angel" },
      { e: "🎅", n: "santa" },
      { e: "🤶", n: "mrs claus" },
      { e: "🦸", n: "superhero" },
      { e: "🦹", n: "supervillain" },
      { e: "🧙", n: "mage wizard" },
      { e: "🧚", n: "fairy" },
      { e: "🧛", n: "vampire" },
      { e: "🧜", n: "merperson" },
      { e: "🧝", n: "elf" },
      { e: "🧞", n: "genie" },
      { e: "🧟", n: "zombie" },
      { e: "💆", n: "massage" },
      { e: "💇", n: "haircut" },
      { e: "🚶", n: "walking" },
      { e: "🧍", n: "standing" },
      { e: "🧎", n: "kneeling" },
      { e: "🏃", n: "running" },
      { e: "💃", n: "dancer woman" },
      { e: "🕺", n: "dancer man" },
      { e: "🕴️", n: "levitate" },
      { e: "👯", n: "dancers" },
      { e: "🧖", n: "sauna" },
      { e: "🧗", n: "climbing" },
      { e: "🤺", n: "fencing" },
      { e: "🏇", n: "horse racing" },
      { e: "⛷️", n: "skier" },
      { e: "🏂", n: "snowboarder" },
      { e: "🏌️", n: "golf" },
      { e: "🏄", n: "surfing" },
      { e: "🚣", n: "rowing" },
      { e: "🏊", n: "swimming" },
      { e: "⛹️", n: "bouncing ball" },
      { e: "🏋️", n: "weight lifting" },
      { e: "🚴", n: "biking" },
      { e: "🚵", n: "mountain bike" },
      { e: "🤸", n: "cartwheel" },
      { e: "🤼", n: "wrestling" },
      { e: "🤽", n: "water polo" },
      { e: "🤾", n: "handball" },
      { e: "🤹", n: "juggling" },
      { e: "🧘", n: "lotus yoga" },
      { e: "🛀", n: "bath" },
      { e: "🛌", n: "sleeping bed" },
      { e: "🧑‍🤝‍🧑", n: "people holding hands" },
      { e: "👭", n: "women holding hands" },
      { e: "👫", n: "woman man holding hands" },
      { e: "👬", n: "men holding hands" },
      { e: "💏", n: "couple kiss" },
      { e: "💑", n: "couple heart" },
      { e: "👪", n: "family" },
      { e: "🗣️", n: "speaking head" },
      { e: "👤", n: "bust" },
      { e: "👥", n: "busts" },
      { e: "🫂", n: "hugging people" },
    ],
  },
  {
    id: "animals",
    label: "Nature",
    icon: "🌿",
    items: [
      { e: "🐶", n: "dog" },
      { e: "🐱", n: "cat" },
      { e: "🐭", n: "mouse" },
      { e: "🐹", n: "hamster" },
      { e: "🐰", n: "rabbit" },
      { e: "🦊", n: "fox" },
      { e: "🐻", n: "bear" },
      { e: "🐼", n: "panda" },
      { e: "🐻‍❄️", n: "polar bear" },
      { e: "🐨", n: "koala" },
      { e: "🐯", n: "tiger" },
      { e: "🦁", n: "lion" },
      { e: "🐮", n: "cow" },
      { e: "🐷", n: "pig" },
      { e: "🐸", n: "frog" },
      { e: "🐵", n: "monkey" },
      { e: "🙈", n: "see no evil" },
      { e: "🙉", n: "hear no evil" },
      { e: "🙊", n: "speak no evil" },
      { e: "🐒", n: "monkey face" },
      { e: "🐔", n: "chicken" },
      { e: "🐧", n: "penguin" },
      { e: "🐦", n: "bird" },
      { e: "🐤", n: "chick" },
      { e: "🦆", n: "duck" },
      { e: "🦅", n: "eagle" },
      { e: "🦉", n: "owl" },
      { e: "🦇", n: "bat" },
      { e: "🐺", n: "wolf" },
      { e: "🐗", n: "boar" },
      { e: "🐴", n: "horse" },
      { e: "🦄", n: "unicorn" },
      { e: "🐝", n: "bee" },
      { e: "🐛", n: "bug" },
      { e: "🦋", n: "butterfly" },
      { e: "🐌", n: "snail" },
      { e: "🐞", n: "ladybug" },
      { e: "🐜", n: "ant" },
      { e: "🦟", n: "mosquito" },
      { e: "🦗", n: "cricket" },
      { e: "🕷️", n: "spider" },
      { e: "🦂", n: "scorpion" },
      { e: "🐢", n: "turtle" },
      { e: "🐍", n: "snake" },
      { e: "🦎", n: "lizard" },
      { e: "🦖", n: "t-rex" },
      { e: "🦕", n: "sauropod" },
      { e: "🐙", n: "octopus" },
      { e: "🦑", n: "squid" },
      { e: "🦐", n: "shrimp" },
      { e: "🦞", n: "lobster" },
      { e: "🦀", n: "crab" },
      { e: "🐡", n: "blowfish" },
      { e: "🐠", n: "tropical fish" },
      { e: "🐟", n: "fish" },
      { e: "🐬", n: "dolphin" },
      { e: "🐳", n: "whale" },
      { e: "🐋", n: "whale2" },
      { e: "🦈", n: "shark" },
      { e: "🐊", n: "crocodile" },
      { e: "🐅", n: "tiger2" },
      { e: "🐆", n: "leopard" },
      { e: "🦓", n: "zebra" },
      { e: "🦍", n: "gorilla" },
      { e: "🦧", n: "orangutan" },
      { e: "🐘", n: "elephant" },
      { e: "🦣", n: "mammoth" },
      { e: "🦏", n: "rhino" },
      { e: "🦛", n: "hippo" },
      { e: "🐪", n: "camel" },
      { e: "🐫", n: "two hump camel" },
      { e: "🦒", n: "giraffe" },
      { e: "🦘", n: "kangaroo" },
      { e: "🦬", n: "bison" },
      { e: "🐃", n: "water buffalo" },
      { e: "🐂", n: "ox" },
      { e: "🐄", n: "cow2" },
      { e: "🐎", n: "racehorse" },
      { e: "🐖", n: "pig2" },
      { e: "🐏", n: "ram" },
      { e: "🐑", n: "sheep" },
      { e: "🦙", n: "llama" },
      { e: "🐐", n: "goat" },
      { e: "🦌", n: "deer" },
      { e: "🐕", n: "dog2" },
      { e: "🐩", n: "poodle" },
      { e: "🦮", n: "guide dog" },
      { e: "🐈", n: "cat2" },
      { e: "🪶", n: "feather" },
      { e: "🐓", n: "rooster" },
      { e: "🦃", n: "turkey" },
      { e: "🦤", n: "dodo" },
      { e: "🦚", n: "peacock" },
      { e: "🦜", n: "parrot" },
      { e: "🦢", n: "swan" },
      { e: "🦩", n: "flamingo" },
      { e: "🕊️", n: "dove" },
      { e: "🐇", n: "rabbit2" },
      { e: "🦝", n: "raccoon" },
      { e: "🦨", n: "skunk" },
      { e: "🦡", n: "badger" },
      { e: "🦫", n: "beaver" },
      { e: "🦦", n: "otter" },
      { e: "🦥", n: "sloth" },
      { e: "🐁", n: "mouse2" },
      { e: "🐀", n: "rat" },
      { e: "🐿️", n: "chipmunk" },
      { e: "🦔", n: "hedgehog" },
      { e: "🐾", n: "paw prints" },
      { e: "🐉", n: "dragon" },
      { e: "🐲", n: "dragon face" },
      { e: "🌵", n: "cactus" },
      { e: "🎄", n: "christmas tree" },
      { e: "🌲", n: "evergreen" },
      { e: "🌳", n: "deciduous" },
      { e: "🌴", n: "palm" },
      { e: "🪵", n: "wood" },
      { e: "🌱", n: "seedling" },
      { e: "🌿", n: "herb" },
      { e: "☘️", n: "shamrock" },
      { e: "🍀", n: "four leaf clover" },
      { e: "🎍", n: "bamboo" },
      { e: "🪴", n: "potted plant" },
      { e: "🎋", n: "tanabata" },
      { e: "🍃", n: "leaves" },
      { e: "🍂", n: "fallen leaf" },
      { e: "🍁", n: "maple" },
      { e: "🍄", n: "mushroom" },
      { e: "🐚", n: "shell" },
      { e: "🪨", n: "rock" },
      { e: "🌾", n: "rice ear" },
      { e: "💐", n: "bouquet" },
      { e: "🌷", n: "tulip" },
      { e: "🌹", n: "rose" },
      { e: "🥀", n: "wilted" },
      { e: "🌺", n: "hibiscus" },
      { e: "🌸", n: "cherry blossom" },
      { e: "🌼", n: "blossom" },
      { e: "🌻", n: "sunflower" },
      { e: "🌞", n: "sun face" },
      { e: "🌝", n: "full moon face" },
      { e: "🌛", n: "first quarter moon face" },
      { e: "🌜", n: "last quarter moon face" },
      { e: "🌚", n: "new moon face" },
      { e: "🌕", n: "full moon" },
      { e: "🌖", n: "waning gibbous" },
      { e: "🌗", n: "last quarter" },
      { e: "🌘", n: "waning crescent" },
      { e: "🌑", n: "new moon" },
      { e: "🌒", n: "waxing crescent" },
      { e: "🌓", n: "first quarter" },
      { e: "🌔", n: "waxing gibbous" },
      { e: "🌙", n: "crescent moon" },
      { e: "🌎", n: "earth americas" },
      { e: "🌍", n: "earth africa" },
      { e: "🌏", n: "earth asia" },
      { e: "🪐", n: "ringed planet" },
      { e: "💫", n: "dizzy star" },
      { e: "⭐", n: "star" },
      { e: "🌟", n: "glowing star" },
      { e: "✨", n: "sparkles" },
      { e: "⚡", n: "zap lightning" },
      { e: "☄️", n: "comet" },
      { e: "💥", n: "boom" },
      { e: "🔥", n: "fire" },
      { e: "🌪️", n: "tornado" },
      { e: "🌈", n: "rainbow" },
      { e: "☀️", n: "sun" },
      { e: "🌤️", n: "sun behind small cloud" },
      { e: "⛅", n: "partly cloudy" },
      { e: "🌥️", n: "sun behind large cloud" },
      { e: "☁️", n: "cloud" },
      { e: "🌦️", n: "sun rain" },
      { e: "🌧️", n: "cloud rain" },
      { e: "⛈️", n: "thunder cloud rain" },
      { e: "🌩️", n: "cloud lightning" },
      { e: "🌨️", n: "cloud snow" },
      { e: "❄️", n: "snowflake" },
      { e: "☃️", n: "snowman" },
      { e: "⛄", n: "snowman without snow" },
      { e: "🌬️", n: "wind face" },
      { e: "💨", n: "dash" },
      { e: "💧", n: "droplet" },
      { e: "💦", n: "sweat drops" },
      { e: "☔", n: "umbrella rain" },
      { e: "☂️", n: "umbrella" },
      { e: "🌊", n: "ocean wave" },
      { e: "🌫️", n: "fog" },
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "🍔",
    items: [
      { e: "🍏", n: "green apple" },
      { e: "🍎", n: "red apple" },
      { e: "🍐", n: "pear" },
      { e: "🍊", n: "tangerine orange" },
      { e: "🍋", n: "lemon" },
      { e: "🍌", n: "banana" },
      { e: "🍉", n: "watermelon" },
      { e: "🍇", n: "grapes" },
      { e: "🍓", n: "strawberry" },
      { e: "🫐", n: "blueberries" },
      { e: "🍈", n: "melon" },
      { e: "🍒", n: "cherries" },
      { e: "🍑", n: "peach" },
      { e: "🥭", n: "mango" },
      { e: "🍍", n: "pineapple" },
      { e: "🥥", n: "coconut" },
      { e: "🥝", n: "kiwi" },
      { e: "🍅", n: "tomato" },
      { e: "🍆", n: "eggplant" },
      { e: "🥑", n: "avocado" },
      { e: "🥦", n: "broccoli" },
      { e: "🥬", n: "leafy green" },
      { e: "🥒", n: "cucumber" },
      { e: "🌶️", n: "hot pepper" },
      { e: "🫑", n: "bell pepper" },
      { e: "🌽", n: "corn" },
      { e: "🥕", n: "carrot" },
      { e: "🫒", n: "olive" },
      { e: "🧄", n: "garlic" },
      { e: "🧅", n: "onion" },
      { e: "🥔", n: "potato" },
      { e: "🍠", n: "sweet potato" },
      { e: "🥐", n: "croissant" },
      { e: "🥯", n: "bagel" },
      { e: "🍞", n: "bread" },
      { e: "🥖", n: "baguette" },
      { e: "🥨", n: "pretzel" },
      { e: "🧀", n: "cheese" },
      { e: "🥚", n: "egg" },
      { e: "🍳", n: "cooking fried egg" },
      { e: "🧈", n: "butter" },
      { e: "🥞", n: "pancakes" },
      { e: "🧇", n: "waffle" },
      { e: "🥓", n: "bacon" },
      { e: "🥩", n: "cut of meat" },
      { e: "🍗", n: "poultry leg" },
      { e: "🍖", n: "meat on bone" },
      { e: "🦴", n: "bone food" },
      { e: "🌭", n: "hot dog" },
      { e: "🍔", n: "hamburger" },
      { e: "🍟", n: "fries" },
      { e: "🍕", n: "pizza" },
      { e: "🫓", n: "flatbread" },
      { e: "🥪", n: "sandwich" },
      { e: "🥙", n: "stuffed flatbread" },
      { e: "🧆", n: "falafel" },
      { e: "🌮", n: "taco" },
      { e: "🌯", n: "burrito" },
      { e: "🫔", n: "tamale" },
      { e: "🥗", n: "salad" },
      { e: "🥘", n: "shallow pan" },
      { e: "🫕", n: "fondue" },
      { e: "🥫", n: "canned food" },
      { e: "🍝", n: "spaghetti" },
      { e: "🍜", n: "ramen" },
      { e: "🍲", n: "stew" },
      { e: "🍛", n: "curry" },
      { e: "🍣", n: "sushi" },
      { e: "🍱", n: "bento" },
      { e: "🥟", n: "dumpling" },
      { e: "🦪", n: "oyster" },
      { e: "🍤", n: "fried shrimp" },
      { e: "🍙", n: "rice ball" },
      { e: "🍚", n: "cooked rice" },
      { e: "🍘", n: "rice cracker" },
      { e: "🍥", n: "fish cake" },
      { e: "🥠", n: "fortune cookie" },
      { e: "🥮", n: "moon cake" },
      { e: "🍢", n: "oden" },
      { e: "🍡", n: "dango" },
      { e: "🍧", n: "shaved ice" },
      { e: "🍨", n: "ice cream" },
      { e: "🍦", n: "soft ice cream" },
      { e: "🥧", n: "pie" },
      { e: "🧁", n: "cupcake" },
      { e: "🍰", n: "cake" },
      { e: "🎂", n: "birthday" },
      { e: "🍮", n: "custard" },
      { e: "🍭", n: "lollipop" },
      { e: "🍬", n: "candy" },
      { e: "🍫", n: "chocolate" },
      { e: "🍿", n: "popcorn" },
      { e: "🍩", n: "doughnut" },
      { e: "🍪", n: "cookie" },
      { e: "🌰", n: "chestnut" },
      { e: "🥜", n: "peanuts" },
      { e: "🍯", n: "honey" },
      { e: "🥛", n: "milk" },
      { e: "🍼", n: "baby bottle" },
      { e: "🫖", n: "teapot" },
      { e: "☕", n: "coffee" },
      { e: "🍵", n: "tea" },
      { e: "🧃", n: "juice box" },
      { e: "🥤", n: "cup straw" },
      { e: "🧋", n: "bubble tea" },
      { e: "🍶", n: "sake" },
      { e: "🍺", n: "beer" },
      { e: "🍻", n: "beers" },
      { e: "🥂", n: "clinking glasses" },
      { e: "🍷", n: "wine" },
      { e: "🥃", n: "tumbler" },
      { e: "🍸", n: "cocktail" },
      { e: "🍹", n: "tropical drink" },
      { e: "🧉", n: "mate" },
      { e: "🍾", n: "champagne" },
      { e: "🧊", n: "ice" },
      { e: "🥄", n: "spoon" },
      { e: "🍴", n: "fork knife" },
      { e: "🍽️", n: "plate utensils" },
      { e: "🥣", n: "bowl spoon" },
      { e: "🥡", n: "takeout" },
      { e: "🥢", n: "chopsticks" },
      { e: "🧂", n: "salt" },
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icon: "✈️",
    items: [
      { e: "🚗", n: "car" },
      { e: "🚕", n: "taxi" },
      { e: "🚙", n: "suv" },
      { e: "🚌", n: "bus" },
      { e: "🚎", n: "trolleybus" },
      { e: "🏎️", n: "race car" },
      { e: "🚓", n: "police car" },
      { e: "🚑", n: "ambulance" },
      { e: "🚒", n: "fire engine" },
      { e: "🚐", n: "minibus" },
      { e: "🛻", n: "pickup" },
      { e: "🚚", n: "truck" },
      { e: "🚛", n: "articulated lorry" },
      { e: "🚜", n: "tractor" },
      { e: "🦯", n: "white cane" },
      { e: "🦽", n: "manual wheelchair" },
      { e: "🦼", n: "motorized wheelchair" },
      { e: "🛴", n: "kick scooter" },
      { e: "🚲", n: "bike" },
      { e: "🛵", n: "motor scooter" },
      { e: "🏍️", n: "motorcycle" },
      { e: "🛺", n: "auto rickshaw" },
      { e: "🚨", n: "rotating light" },
      { e: "🚔", n: "oncoming police" },
      { e: "🚍", n: "oncoming bus" },
      { e: "🚘", n: "oncoming car" },
      { e: "🚖", n: "oncoming taxi" },
      { e: "🚡", n: "aerial tramway" },
      { e: "🚠", n: "mountain cableway" },
      { e: "🚟", n: "suspension railway" },
      { e: "🚃", n: "railway car" },
      { e: "🚋", n: "tram car" },
      { e: "🚞", n: "mountain railway" },
      { e: "🚝", n: "monorail" },
      { e: "🚄", n: "bullet train" },
      { e: "🚅", n: "bullet train front" },
      { e: "🚈", n: "light rail" },
      { e: "🚂", n: "locomotive" },
      { e: "🚆", n: "train" },
      { e: "🚇", n: "metro" },
      { e: "🚊", n: "tram" },
      { e: "🚉", n: "station" },
      { e: "✈️", n: "airplane" },
      { e: "🛫", n: "flight departure" },
      { e: "🛬", n: "flight arrival" },
      { e: "🛩️", n: "small airplane" },
      { e: "💺", n: "seat" },
      { e: "🛰️", n: "satellite" },
      { e: "🚀", n: "rocket" },
      { e: "🛸", n: "flying saucer" },
      { e: "🚁", n: "helicopter" },
      { e: "🛶", n: "canoe" },
      { e: "⛵", n: "sailboat" },
      { e: "🚤", n: "speedboat" },
      { e: "🛥️", n: "motor boat" },
      { e: "🛳️", n: "passenger ship" },
      { e: "⛴️", n: "ferry" },
      { e: "🚢", n: "ship" },
      { e: "⚓", n: "anchor" },
      { e: "🪝", n: "hook" },
      { e: "⛽", n: "fuel" },
      { e: "🚧", n: "construction barrier" },
      { e: "🚦", n: "traffic light" },
      { e: "🚥", n: "horizontal traffic light" },
      { e: "🚏", n: "bus stop" },
      { e: "🗺️", n: "world map" },
      { e: "🗿", n: "moai" },
      { e: "🗽", n: "statue of liberty" },
      { e: "🗼", n: "tokyo tower" },
      { e: "🏰", n: "castle" },
      { e: "🏯", n: "japanese castle" },
      { e: "🏟️", n: "stadium" },
      { e: "🎡", n: "ferris wheel" },
      { e: "🎢", n: "roller coaster" },
      { e: "🎠", n: "carousel" },
      { e: "⛲", n: "fountain" },
      { e: "⛱️", n: "umbrella beach" },
      { e: "🏖️", n: "beach" },
      { e: "🏝️", n: "island" },
      { e: "🏜️", n: "desert" },
      { e: "🌋", n: "volcano" },
      { e: "⛰️", n: "mountain" },
      { e: "🏔️", n: "snow mountain" },
      { e: "🗻", n: "mount fuji" },
      { e: "🏕️", n: "camping" },
      { e: "⛺", n: "tent" },
      { e: "🏠", n: "house" },
      { e: "🏡", n: "house garden" },
      { e: "🏢", n: "office" },
      { e: "🏣", n: "post office japan" },
      { e: "🏤", n: "post office" },
      { e: "🏥", n: "hospital" },
      { e: "🏦", n: "bank" },
      { e: "🏨", n: "hotel" },
      { e: "🏩", n: "love hotel" },
      { e: "🏪", n: "convenience store" },
      { e: "🏫", n: "school" },
      { e: "🏬", n: "department store" },
      { e: "🏭", n: "factory" },
      { e: "🏯", n: "japanese castle2" },
      { e: "💒", n: "wedding" },
      { e: "⛪", n: "church" },
      { e: "🕌", n: "mosque" },
      { e: "🛕", n: "hindu temple" },
      { e: "🕍", n: "synagogue" },
      { e: "⛩️", n: "shinto shrine" },
      { e: "🕋", n: "kaaba" },
    ],
  },
  {
    id: "activities",
    label: "Activities",
    icon: "⚽",
    items: [
      { e: "⚽", n: "soccer" },
      { e: "🏀", n: "basketball" },
      { e: "🏈", n: "football" },
      { e: "⚾", n: "baseball" },
      { e: "🥎", n: "softball" },
      { e: "🎾", n: "tennis" },
      { e: "🏐", n: "volleyball" },
      { e: "🏉", n: "rugby" },
      { e: "🥏", n: "flying disc" },
      { e: "🎱", n: "8ball" },
      { e: "🪀", n: "yo yo" },
      { e: "🏓", n: "ping pong" },
      { e: "🏸", n: "badminton" },
      { e: "🏒", n: "ice hockey" },
      { e: "🏑", n: "field hockey" },
      { e: "🥍", n: "lacrosse" },
      { e: "🏏", n: "cricket" },
      { e: "🪃", n: "boomerang" },
      { e: "🥅", n: "goal" },
      { e: "⛳", n: "golf hole" },
      { e: "🪁", n: "kite" },
      { e: "🏹", n: "bow arrow" },
      { e: "🎣", n: "fishing" },
      { e: "🤿", n: "diving mask" },
      { e: "🥊", n: "boxing" },
      { e: "🥋", n: "martial arts" },
      { e: "🎽", n: "running shirt" },
      { e: "🛹", n: "skateboard" },
      { e: "🛼", n: "roller skate" },
      { e: "🛷", n: "sled" },
      { e: "⛸️", n: "ice skate" },
      { e: "🥌", n: "curling" },
      { e: "🎿", n: "skis" },
      { e: "⛷️", n: "skier activity" },
      { e: "🏂", n: "snowboard" },
      { e: "🪂", n: "parachute" },
      { e: "🏋️", n: "weights" },
      { e: "🤼", n: "wrestle" },
      { e: "🤸", n: "cartwheel activity" },
      { e: "⛹️", n: "basketball person" },
      { e: "🤺", n: "fencer" },
      { e: "🤾", n: "handball activity" },
      { e: "🏌️", n: "golfer" },
      { e: "🏇", n: "horse race" },
      { e: "🧘", n: "meditation" },
      { e: "🏄", n: "surfer" },
      { e: "🏊", n: "swimmer" },
      { e: "🤽", n: "water polo activity" },
      { e: "🚣", n: "rowboat" },
      { e: "🧗", n: "climber" },
      { e: "🚵", n: "mountain biker" },
      { e: "🚴", n: "bicyclist" },
      { e: "🏆", n: "trophy" },
      { e: "🥇", n: "gold medal" },
      { e: "🥈", n: "silver medal" },
      { e: "🥉", n: "bronze medal" },
      { e: "🏅", n: "sports medal" },
      { e: "🎖️", n: "military medal" },
      { e: "🏵️", n: "rosette" },
      { e: "🎗️", n: "reminder ribbon" },
      { e: "🎫", n: "ticket" },
      { e: "🎟️", n: "admission tickets" },
      { e: "🎪", n: "circus" },
      { e: "🤹", n: "juggle" },
      { e: "🎭", n: "performing arts" },
      { e: "🩰", n: "ballet" },
      { e: "🎨", n: "art palette" },
      { e: "🎬", n: "clapper" },
      { e: "🎤", n: "microphone" },
      { e: "🎧", n: "headphones" },
      { e: "🎼", n: "musical score" },
      { e: "🎹", n: "piano" },
      { e: "🥁", n: "drum" },
      { e: "🪘", n: "long drum" },
      { e: "🎷", n: "saxophone" },
      { e: "🎺", n: "trumpet" },
      { e: "🎸", n: "guitar" },
      { e: "🪕", n: "banjo" },
      { e: "🎻", n: "violin" },
      { e: "🪗", n: "accordion" },
      { e: "🎲", n: "dice" },
      { e: "♟️", n: "chess" },
      { e: "🎯", n: "dart" },
      { e: "🎳", n: "bowling" },
      { e: "🎮", n: "video game" },
      { e: "🎰", n: "slot machine" },
      { e: "🧩", n: "puzzle" },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    items: [
      { e: "⌚", n: "watch" },
      { e: "📱", n: "phone mobile" },
      { e: "📲", n: "phone arrow" },
      { e: "💻", n: "laptop computer" },
      { e: "⌨️", n: "keyboard" },
      { e: "🖥️", n: "desktop computer" },
      { e: "🖨️", n: "printer" },
      { e: "🖱️", n: "mouse computer" },
      { e: "🖲️", n: "trackball" },
      { e: "🕹️", n: "joystick" },
      { e: "🗜️", n: "clamp" },
      { e: "💽", n: "minidisc" },
      { e: "💾", n: "floppy" },
      { e: "💿", n: "cd" },
      { e: "📀", n: "dvd" },
      { e: "📼", n: "vhs" },
      { e: "📷", n: "camera" },
      { e: "📸", n: "camera flash" },
      { e: "📹", n: "video camera" },
      { e: "🎥", n: "movie camera" },
      { e: "📽️", n: "film projector" },
      { e: "🎞️", n: "film frames" },
      { e: "📞", n: "telephone receiver" },
      { e: "☎️", n: "telephone" },
      { e: "📟", n: "pager" },
      { e: "📠", n: "fax" },
      { e: "📺", n: "tv" },
      { e: "📻", n: "radio" },
      { e: "🎙️", n: "studio mic" },
      { e: "🎚️", n: "level slider" },
      { e: "🎛️", n: "control knobs" },
      { e: "🧭", n: "compass" },
      { e: "⏱️", n: "stopwatch" },
      { e: "⏲️", n: "timer" },
      { e: "⏰", n: "alarm clock" },
      { e: "🕰️", n: "mantelpiece clock" },
      { e: "⌛", n: "hourglass" },
      { e: "⏳", n: "hourglass flowing" },
      { e: "📡", n: "satellite antenna" },
      { e: "🔋", n: "battery" },
      { e: "🔌", n: "electric plug" },
      { e: "💡", n: "light bulb idea" },
      { e: "🔦", n: "flashlight" },
      { e: "🕯️", n: "candle" },
      { e: "🪔", n: "diya lamp" },
      { e: "🧯", n: "fire extinguisher" },
      { e: "🛢️", n: "oil drum" },
      { e: "💸", n: "money with wings" },
      { e: "💵", n: "dollar" },
      { e: "💴", n: "yen" },
      { e: "💶", n: "euro" },
      { e: "💷", n: "pound" },
      { e: "🪙", n: "coin" },
      { e: "💰", n: "money bag" },
      { e: "💳", n: "credit card" },
      { e: "💎", n: "gem" },
      { e: "⚖️", n: "balance scale" },
      { e: "🪜", n: "ladder" },
      { e: "🧰", n: "toolbox" },
      { e: "🪛", n: "screwdriver" },
      { e: "🔧", n: "wrench" },
      { e: "🔨", n: "hammer" },
      { e: "⚒️", n: "hammer pick" },
      { e: "🛠️", n: "hammer wrench" },
      { e: "⛏️", n: "pick" },
      { e: "🪚", n: "carpentry saw" },
      { e: "🔩", n: "nut and bolt" },
      { e: "⚙️", n: "gear" },
      { e: "🪤", n: "mouse trap" },
      { e: "🧱", n: "brick" },
      { e: "⛓️", n: "chains" },
      { e: "🧲", n: "magnet" },
      { e: "🔫", n: "water pistol" },
      { e: "💣", n: "bomb" },
      { e: "🧨", n: "firecracker" },
      { e: "🪓", n: "axe" },
      { e: "🔪", n: "kitchen knife" },
      { e: "🗡️", n: "dagger" },
      { e: "⚔️", n: "crossed swords" },
      { e: "🛡️", n: "shield" },
      { e: "🚬", n: "cigarette" },
      { e: "⚰️", n: "coffin" },
      { e: "🪦", n: "headstone" },
      { e: "⚱️", n: "funeral urn" },
      { e: "🏺", n: "amphora" },
      { e: "🔮", n: "crystal ball" },
      { e: "📿", n: "prayer beads" },
      { e: "🧿", n: "nazar" },
      { e: "💈", n: "barber" },
      { e: "⚗️", n: "alembic" },
      { e: "🔭", n: "telescope" },
      { e: "🔬", n: "microscope" },
      { e: "🕳️", n: "hole" },
      { e: "🩹", n: "adhesive bandage" },
      { e: "🩺", n: "stethoscope" },
      { e: "💊", n: "pill" },
      { e: "💉", n: "syringe" },
      { e: "🩸", n: "drop of blood" },
      { e: "🧬", n: "dna" },
      { e: "🦠", n: "microbe" },
      { e: "🧫", n: "petri dish" },
      { e: "🧪", n: "test tube" },
      { e: "🌡️", n: "thermometer object" },
      { e: "🧹", n: "broom" },
      { e: "🧺", n: "basket" },
      { e: "🧻", n: "roll of paper" },
      { e: "🚽", n: "toilet" },
      { e: "🚰", n: "potable water" },
      { e: "🚿", n: "shower" },
      { e: "🛁", n: "bathtub" },
      { e: "🛀", n: "person bathing" },
      { e: "🧼", n: "soap" },
      { e: "🪥", n: "toothbrush" },
      { e: "🪒", n: "razor" },
      { e: "🧽", n: "sponge" },
      { e: "🪣", n: "bucket" },
      { e: "🧴", n: "lotion" },
      { e: "🛎️", n: "bellhop" },
      { e: "🔑", n: "key" },
      { e: "🗝️", n: "old key" },
      { e: "🚪", n: "door" },
      { e: "🪑", n: "chair" },
      { e: "🛋️", n: "couch" },
      { e: "🛏️", n: "bed" },
      { e: "🛌", n: "person in bed" },
      { e: "🧸", n: "teddy bear" },
      { e: "🖼️", n: "framed picture" },
      { e: "🛍️", n: "shopping bags" },
      { e: "🛒", n: "shopping cart" },
      { e: "🎁", n: "gift" },
      { e: "🎈", n: "balloon" },
      { e: "🎏", n: "carp streamer" },
      { e: "🎀", n: "ribbon" },
      { e: "🪄", n: "magic wand" },
      { e: "🪅", n: "pinata" },
      { e: "🎊", n: "confetti ball" },
      { e: "🎉", n: "party popper" },
      { e: "🎎", n: "dolls" },
      { e: "🏮", n: "red paper lantern" },
      { e: "🎐", n: "wind chime" },
      { e: "🧧", n: "red envelope" },
      { e: "✉️", n: "envelope" },
      { e: "📩", n: "envelope arrow" },
      { e: "📨", n: "incoming envelope" },
      { e: "📧", n: "email" },
      { e: "💌", n: "love letter" },
      { e: "📥", n: "inbox" },
      { e: "📤", n: "outbox" },
      { e: "📦", n: "package" },
      { e: "🏷️", n: "label" },
      { e: "🪧", n: "placard" },
      { e: "📪", n: "mailbox closed" },
      { e: "📫", n: "mailbox" },
      { e: "📬", n: "mailbox with mail" },
      { e: "📭", n: "mailbox with no mail" },
      { e: "📮", n: "postbox" },
      { e: "📯", n: "postal horn" },
      { e: "📜", n: "scroll" },
      { e: "📃", n: "page curl" },
      { e: "📄", n: "page facing up" },
      { e: "📑", n: "bookmark tabs" },
      { e: "🧾", n: "receipt" },
      { e: "📊", n: "bar chart" },
      { e: "📈", n: "chart up" },
      { e: "📉", n: "chart down" },
      { e: "🗒️", n: "spiral notepad" },
      { e: "🗓️", n: "spiral calendar" },
      { e: "📆", n: "tear off calendar" },
      { e: "📅", n: "calendar" },
      { e: "🗑️", n: "wastebasket" },
      { e: "📇", n: "card index" },
      { e: "🗃️", n: "card file box" },
      { e: "🗳️", n: "ballot box" },
      { e: "🗄️", n: "file cabinet" },
      { e: "📋", n: "clipboard" },
      { e: "📁", n: "file folder" },
      { e: "📂", n: "open file folder" },
      { e: "🗂️", n: "card index dividers" },
      { e: "🗞️", n: "rolled newspaper" },
      { e: "📰", n: "newspaper" },
      { e: "📓", n: "notebook" },
      { e: "📔", n: "notebook decorative" },
      { e: "📒", n: "ledger" },
      { e: "📕", n: "closed book" },
      { e: "📗", n: "green book" },
      { e: "📘", n: "blue book" },
      { e: "📙", n: "orange book" },
      { e: "📚", n: "books" },
      { e: "📖", n: "open book" },
      { e: "🔖", n: "bookmark" },
      { e: "🧷", n: "safety pin" },
      { e: "🔗", n: "link" },
      { e: "📎", n: "paperclip" },
      { e: "🖇️", n: "linked paperclips" },
      { e: "📐", n: "triangular ruler" },
      { e: "📏", n: "straight ruler" },
      { e: "🧮", n: "abacus" },
      { e: "📌", n: "pushpin" },
      { e: "📍", n: "round pushpin" },
      { e: "✂️", n: "scissors" },
      { e: "🖊️", n: "pen" },
      { e: "🖋️", n: "fountain pen" },
      { e: "✒️", n: "black nib" },
      { e: "🖌️", n: "paintbrush" },
      { e: "🖍️", n: "crayon" },
      { e: "📝", n: "memo note" },
      { e: "✏️", n: "pencil" },
      { e: "🔍", n: "magnifying glass left" },
      { e: "🔎", n: "magnifying glass right" },
      { e: "🔏", n: "locked with pen" },
      { e: "🔐", n: "locked with key" },
      { e: "🔒", n: "locked" },
      { e: "🔓", n: "unlocked" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "❤️",
    items: [
      { e: "❤️", n: "red heart" },
      { e: "🧡", n: "orange heart" },
      { e: "💛", n: "yellow heart" },
      { e: "💚", n: "green heart" },
      { e: "💙", n: "blue heart" },
      { e: "💜", n: "purple heart" },
      { e: "🖤", n: "black heart" },
      { e: "🤍", n: "white heart" },
      { e: "🤎", n: "brown heart" },
      { e: "💔", n: "broken heart" },
      { e: "❣️", n: "heart exclamation" },
      { e: "💕", n: "two hearts" },
      { e: "💞", n: "revolving hearts" },
      { e: "💓", n: "beating heart" },
      { e: "💗", n: "growing heart" },
      { e: "💖", n: "sparkling heart" },
      { e: "💘", n: "heart arrow" },
      { e: "💝", n: "heart ribbon" },
      { e: "💟", n: "heart decoration" },
      { e: "☮️", n: "peace" },
      { e: "✝️", n: "latin cross" },
      { e: "☪️", n: "star and crescent" },
      { e: "🕉️", n: "om" },
      { e: "☸️", n: "wheel of dharma" },
      { e: "✡️", n: "star of david" },
      { e: "🔯", n: "dotted six pointed star" },
      { e: "🕎", n: "menorah" },
      { e: "☯️", n: "yin yang" },
      { e: "☦️", n: "orthodox cross" },
      { e: "🛐", n: "place of worship" },
      { e: "⛎", n: "ophiuchus" },
      { e: "♈", n: "aries" },
      { e: "♉", n: "taurus" },
      { e: "♊", n: "gemini" },
      { e: "♋", n: "cancer" },
      { e: "♌", n: "leo" },
      { e: "♍", n: "virgo" },
      { e: "♎", n: "libra" },
      { e: "♏", n: "scorpio" },
      { e: "♐", n: "sagittarius" },
      { e: "♑", n: "capricorn" },
      { e: "♒", n: "aquarius" },
      { e: "♓", n: "pisces" },
      { e: "🆔", n: "id" },
      { e: "⚛️", n: "atom" },
      { e: "🉑", n: "accept" },
      { e: "☢️", n: "radioactive" },
      { e: "☣️", n: "biohazard" },
      { e: "📴", n: "mobile off" },
      { e: "📳", n: "vibration mode" },
      { e: "🈶", n: "not free of charge" },
      { e: "🈚", n: "free of charge" },
      { e: "🈸", n: "application" },
      { e: "🈺", n: "open for business" },
      { e: "🈷️", n: "monthly amount" },
      { e: "✴️", n: "eight pointed star" },
      { e: "🆚", n: "vs" },
      { e: "💮", n: "white flower" },
      { e: "🉐", n: "bargain" },
      { e: "㊙️", n: "secret" },
      { e: "㊗️", n: "congratulations" },
      { e: "🈴", n: "passing grade" },
      { e: "🈵", n: "no vacancy" },
      { e: "🈹", n: "discount" },
      { e: "🈲", n: "prohibited" },
      { e: "🅰️", n: "a button" },
      { e: "🅱️", n: "b button" },
      { e: "🆎", n: "ab button" },
      { e: "🆑", n: "cl" },
      { e: "🅾️", n: "o button" },
      { e: "🆘", n: "sos" },
      { e: "❌", n: "cross mark x" },
      { e: "⭕", n: "hollow red circle" },
      { e: "🛑", n: "stop sign" },
      { e: "⛔", n: "no entry" },
      { e: "📛", n: "name badge" },
      { e: "🚫", n: "prohibited no" },
      { e: "💯", n: "hundred" },
      { e: "💢", n: "anger" },
      { e: "♨️", n: "hotsprings" },
      { e: "🚷", n: "no pedestrians" },
      { e: "🚯", n: "no littering" },
      { e: "🚳", n: "no bicycles" },
      { e: "🚱", n: "non potable water" },
      { e: "🔞", n: "no one under eighteen" },
      { e: "📵", n: "no mobile phones" },
      { e: "🚭", n: "no smoking" },
      { e: "❗", n: "exclamation" },
      { e: "❕", n: "white exclamation" },
      { e: "❓", n: "question" },
      { e: "❔", n: "white question" },
      { e: "‼️", n: "double exclamation" },
      { e: "⁉️", n: "exclamation question" },
      { e: "🔅", n: "dim button" },
      { e: "🔆", n: "bright button" },
      { e: "〽️", n: "part alternation mark" },
      { e: "⚠️", n: "warning" },
      { e: "🚸", n: "children crossing" },
      { e: "🔱", n: "trident" },
      { e: "⚜️", n: "fleur de lis" },
      { e: "🔰", n: "japanese beginner" },
      { e: "♻️", n: "recycling" },
      { e: "✅", n: "check mark button" },
      { e: "🈯", n: "japanese reserved" },
      { e: "💹", n: "chart increasing yen" },
      { e: "❇️", n: "sparkle" },
      { e: "✳️", n: "eight spoked asterisk" },
      { e: "❎", n: "cross mark button" },
      { e: "🌐", n: "globe meridians" },
      { e: "💠", n: "diamond with a dot" },
      { e: "Ⓜ️", n: "circled m" },
      { e: "🌀", n: "cyclone" },
      { e: "💤", n: "zzz" },
      { e: "🏧", n: "atm" },
      { e: "🚾", n: "water closet" },
      { e: "♿", n: "wheelchair" },
      { e: "🅿️", n: "p button" },
      { e: "🛗", n: "elevator" },
      { e: "🈳", n: "japanese vacancy" },
      { e: "🈂️", n: "japanese service charge" },
      { e: "🛂", n: "passport control" },
      { e: "🛃", n: "customs" },
      { e: "🛄", n: "baggage claim" },
      { e: "🛅", n: "left luggage" },
      { e: "🚹", n: "mens room" },
      { e: "🚺", n: "womens room" },
      { e: "🚼", n: "baby symbol" },
      { e: "⚧️", n: "transgender symbol" },
      { e: "🚻", n: "restroom" },
      { e: "🚮", n: "litter in bin" },
      { e: "🎦", n: "cinema" },
      { e: "📶", n: "antenna bars" },
      { e: "🈁", n: "japanese here" },
      { e: "🔣", n: "input symbols" },
      { e: "ℹ️", n: "information" },
      { e: "🔤", n: "input latin letters" },
      { e: "🔡", n: "input latin lowercase" },
      { e: "🔠", n: "input latin uppercase" },
      { e: "🔢", n: "input numbers" },
      { e: "🔟", n: "keycap ten" },
      { e: "🔢", n: "numbers" },
      { e: "#️⃣", n: "keycap number sign" },
      { e: "*️⃣", n: "keycap asterisk" },
      { e: "0️⃣", n: "keycap 0" },
      { e: "1️⃣", n: "keycap 1" },
      { e: "2️⃣", n: "keycap 2" },
      { e: "3️⃣", n: "keycap 3" },
      { e: "4️⃣", n: "keycap 4" },
      { e: "5️⃣", n: "keycap 5" },
      { e: "6️⃣", n: "keycap 6" },
      { e: "7️⃣", n: "keycap 7" },
      { e: "8️⃣", n: "keycap 8" },
      { e: "9️⃣", n: "keycap 9" },
      { e: "⏏️", n: "eject" },
      { e: "▶️", n: "play" },
      { e: "⏸️", n: "pause" },
      { e: "⏯️", n: "play pause" },
      { e: "⏹️", n: "stop button" },
      { e: "⏺️", n: "record" },
      { e: "⏭️", n: "next track" },
      { e: "⏮️", n: "previous track" },
      { e: "⏩", n: "fast forward" },
      { e: "⏪", n: "fast reverse" },
      { e: "⏫", n: "fast up" },
      { e: "⏬", n: "fast down" },
      { e: "◀️", n: "reverse" },
      { e: "🔼", n: "upwards button" },
      { e: "🔽", n: "downwards button" },
      { e: "➡️", n: "right arrow" },
      { e: "⬅️", n: "left arrow" },
      { e: "⬆️", n: "up arrow" },
      { e: "⬇️", n: "down arrow" },
      { e: "↗️", n: "up right arrow" },
      { e: "↘️", n: "down right arrow" },
      { e: "↙️", n: "down left arrow" },
      { e: "↖️", n: "up left arrow" },
      { e: "↕️", n: "up down arrow" },
      { e: "↔️", n: "left right arrow" },
      { e: "↪️", n: "left arrow curving right" },
      { e: "↩️", n: "right arrow curving left" },
      { e: "⤴️", n: "right arrow curving up" },
      { e: "⤵️", n: "right arrow curving down" },
      { e: "🔀", n: "shuffle" },
      { e: "🔁", n: "repeat" },
      { e: "🔂", n: "repeat one" },
      { e: "🔄", n: "counterclockwise" },
      { e: "🔃", n: "clockwise" },
      { e: "🎵", n: "musical note" },
      { e: "🎶", n: "musical notes" },
      { e: "➕", n: "plus" },
      { e: "➖", n: "minus" },
      { e: "➗", n: "divide" },
      { e: "✖️", n: "multiply" },
      { e: "♾️", n: "infinity" },
      { e: "💲", n: "heavy dollar" },
      { e: "💱", n: "currency exchange" },
      { e: "™️", n: "tm" },
      { e: "©️", n: "copyright" },
      { e: "®️", n: "registered" },
      { e: "〰️", n: "wavy dash" },
      { e: "➰", n: "curly loop" },
      { e: "➿", n: "double curly loop" },
      { e: "🔚", n: "end" },
      { e: "🔙", n: "back" },
      { e: "🔛", n: "on" },
      { e: "🔝", n: "top" },
      { e: "🔜", n: "soon" },
      { e: "✔️", n: "check mark" },
      { e: "☑️", n: "check box" },
      { e: "🔘", n: "radio button" },
      { e: "🔴", n: "red circle" },
      { e: "🟠", n: "orange circle" },
      { e: "🟡", n: "yellow circle" },
      { e: "🟢", n: "green circle" },
      { e: "🔵", n: "blue circle" },
      { e: "🟣", n: "purple circle" },
      { e: "⚫", n: "black circle" },
      { e: "⚪", n: "white circle" },
      { e: "🟤", n: "brown circle" },
      { e: "🔺", n: "red triangle up" },
      { e: "🔻", n: "red triangle down" },
      { e: "🔸", n: "small orange diamond" },
      { e: "🔹", n: "small blue diamond" },
      { e: "🔶", n: "large orange diamond" },
      { e: "🔷", n: "large blue diamond" },
      { e: "🔳", n: "white square button" },
      { e: "🔲", n: "black square button" },
      { e: "▪️", n: "black small square" },
      { e: "▫️", n: "white small square" },
      { e: "◾", n: "black medium small square" },
      { e: "◽", n: "white medium small square" },
      { e: "◼️", n: "black medium square" },
      { e: "◻️", n: "white medium square" },
      { e: "🟥", n: "red square" },
      { e: "🟧", n: "orange square" },
      { e: "🟨", n: "yellow square" },
      { e: "🟩", n: "green square" },
      { e: "🟦", n: "blue square" },
      { e: "🟪", n: "purple square" },
      { e: "⬛", n: "black large square" },
      { e: "⬜", n: "white large square" },
      { e: "🟫", n: "brown square" },
      { e: "🔈", n: "speaker low" },
      { e: "🔇", n: "muted speaker" },
      { e: "🔉", n: "speaker medium" },
      { e: "🔊", n: "speaker high" },
      { e: "🔔", n: "bell" },
      { e: "🔕", n: "bell slash" },
      { e: "📣", n: "megaphone" },
      { e: "📢", n: "loudspeaker" },
      { e: "💬", n: "speech balloon" },
      { e: "💭", n: "thought balloon" },
      { e: "🗯️", n: "right anger bubble" },
      { e: "♠️", n: "spade" },
      { e: "♣️", n: "club" },
      { e: "♥️", n: "heart suit" },
      { e: "♦️", n: "diamond suit" },
      { e: "🃏", n: "joker" },
      { e: "🎴", n: "flower playing cards" },
      { e: "🀄", n: "mahjong" },
      { e: "🕐", n: "one oclock" },
      { e: "🕑", n: "two oclock" },
      { e: "🕒", n: "three oclock" },
      { e: "🕓", n: "four oclock" },
      { e: "🕔", n: "five oclock" },
      { e: "🕕", n: "six oclock" },
      { e: "🕖", n: "seven oclock" },
      { e: "🕗", n: "eight oclock" },
      { e: "🕘", n: "nine oclock" },
      { e: "🕙", n: "ten oclock" },
      { e: "🕚", n: "eleven oclock" },
      { e: "🕛", n: "twelve oclock" },
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🏳️",
    items: [
      { e: "🏳️", n: "white flag" },
      { e: "🏴", n: "black flag" },
      { e: "🏁", n: "checkered flag" },
      { e: "🚩", n: "triangular flag" },
      { e: "🏳️‍🌈", n: "rainbow flag" },
      { e: "🏳️‍⚧️", n: "transgender flag" },
      { e: "🏴‍☠️", n: "pirate flag" },
      { e: "🇺🇸", n: "united states usa" },
      { e: "🇬🇧", n: "united kingdom uk" },
      { e: "🇨🇦", n: "canada" },
      { e: "🇲🇽", n: "mexico" },
      { e: "🇧🇷", n: "brazil" },
      { e: "🇦🇷", n: "argentina" },
      { e: "🇨🇱", n: "chile" },
      { e: "🇨🇴", n: "colombia" },
      { e: "🇵🇪", n: "peru" },
      { e: "🇻🇪", n: "venezuela" },
      { e: "🇫🇷", n: "france" },
      { e: "🇩🇪", n: "germany" },
      { e: "🇪🇸", n: "spain" },
      { e: "🇮🇹", n: "italy" },
      { e: "🇵🇹", n: "portugal" },
      { e: "🇳🇱", n: "netherlands" },
      { e: "🇧🇪", n: "belgium" },
      { e: "🇨🇭", n: "switzerland" },
      { e: "🇦🇹", n: "austria" },
      { e: "🇸🇪", n: "sweden" },
      { e: "🇳🇴", n: "norway" },
      { e: "🇩🇰", n: "denmark" },
      { e: "🇫🇮", n: "finland" },
      { e: "🇵🇱", n: "poland" },
      { e: "🇺🇦", n: "ukraine" },
      { e: "🇷🇺", n: "russia" },
      { e: "🇹🇷", n: "turkey" },
      { e: "🇬🇷", n: "greece" },
      { e: "🇮🇪", n: "ireland" },
      { e: "🇮🇸", n: "iceland" },
      { e: "🇨🇳", n: "china" },
      { e: "🇯🇵", n: "japan" },
      { e: "🇰🇷", n: "south korea" },
      { e: "🇰🇵", n: "north korea" },
      { e: "🇮🇳", n: "india" },
      { e: "🇵🇰", n: "pakistan" },
      { e: "🇧🇩", n: "bangladesh" },
      { e: "🇮🇩", n: "indonesia" },
      { e: "🇹🇭", n: "thailand" },
      { e: "🇻🇳", n: "vietnam" },
      { e: "🇵🇭", n: "philippines" },
      { e: "🇲🇾", n: "malaysia" },
      { e: "🇸🇬", n: "singapore" },
      { e: "🇹🇼", n: "taiwan" },
      { e: "🇭🇰", n: "hong kong" },
      { e: "🇦🇺", n: "australia" },
      { e: "🇳🇿", n: "new zealand" },
      { e: "🇿🇦", n: "south africa" },
      { e: "🇪🇬", n: "egypt" },
      { e: "🇳🇬", n: "nigeria" },
      { e: "🇰🇪", n: "kenya" },
      { e: "🇲🇦", n: "morocco" },
      { e: "🇪🇹", n: "ethiopia" },
      { e: "🇸🇦", n: "saudi arabia" },
      { e: "🇦🇪", n: "uae" },
      { e: "🇮🇱", n: "israel" },
      { e: "🇮🇷", n: "iran" },
      { e: "🇮🇶", n: "iraq" },
      { e: "🇪🇺", n: "european union" },
      { e: "🇺🇳", n: "united nations" },
    ],
  },
];

const RECENT_KEY = "grokhub.emoji.recent";
const MAX_RECENT = 24;

export function loadRecentEmojis(): string[] {
  try {
    const raw = localStorage.getItem(RECENT_KEY);
    if (!raw) return [];
    const arr = JSON.parse(raw) as unknown;
    if (!Array.isArray(arr)) return [];
    return arr.filter((x): x is string => typeof x === "string").slice(0, MAX_RECENT);
  } catch {
    return [];
  }
}

export function pushRecentEmoji(emoji: string): string[] {
  const prev = loadRecentEmojis().filter((e) => e !== emoji);
  const next = [emoji, ...prev].slice(0, MAX_RECENT);
  try {
    localStorage.setItem(RECENT_KEY, JSON.stringify(next));
  } catch {
    /* ignore */
  }
  return next;
}

export function searchEmojis(query: string): EmojiItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: EmojiItem[] = [];
  const seen = new Set<string>();
  for (const cat of EMOJI_CATEGORIES) {
    for (const item of cat.items) {
      if (seen.has(item.e)) continue;
      const hay = `${item.n} ${item.k || ""}`.toLowerCase();
      if (hay.includes(q) || item.e.includes(q)) {
        seen.add(item.e);
        out.push(item);
        if (out.length >= 80) return out;
      }
    }
  }
  return out;
}
