/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiGrokRouteImport } from './routes/api/grok'
import { Route as ApiHostRouteImport } from './routes/api/host'
import { Route as ApiUpdateRouteImport } from './routes/api/update'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrokRoute = ApiGrokRouteImport.update({
  id: '/api/grok',
  path: '/api/grok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostRoute = ApiHostRouteImport.update({
  id: '/api/host',
  path: '/api/host',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateRoute = ApiUpdateRouteImport.update({
  id: '/api/update',
  path: '/api/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/grok': typeof ApiGrokRoute
  '/api/host': typeof ApiHostRoute
  '/api/update': typeof ApiUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/grok': typeof ApiGrokRoute
  '/api/host': typeof ApiHostRoute
  '/api/update': typeof ApiUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/grok': typeof ApiGrokRoute
  '/api/host': typeof ApiHostRoute
  '/api/update': typeof ApiUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/api/grok' | '/api/host' | '/api/update' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/grok' | '/api/host' | '/api/update' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/grok'
    | '/api/host'
    | '/api/update'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiGrokRoute: typeof ApiGrokRoute
  ApiHostRoute: typeof ApiHostRoute
  ApiUpdateRoute: typeof ApiUpdateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok': {
      id: '/api/grok'
      path: '/api/grok'
      fullPath: '/api/grok'
      preLoaderRoute: typeof ApiGrokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host': {
      id: '/api/host'
      path: '/api/host'
      fullPath: '/api/host'
      preLoaderRoute: typeof ApiHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update': {
      id: '/api/update'
      path: '/api/update'
      fullPath: '/api/update'
      preLoaderRoute: typeof ApiUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiGrokRoute: ApiGrokRoute,
  ApiHostRoute: ApiHostRoute,
  ApiUpdateRoute: ApiUpdateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
